import 'dart:math' as math;

import '../../domain/entities/entities.dart';
import '../mock/world_cup_mock_data.dart';
import 'simulation/simulation_models.dart';
import 'simulation/simulation_match_engine.dart';
import 'simulation/simulation_bracket_builder.dart';

/// Result of a full tournament Monte Carlo simulation.
///
/// Contains per-team probability estimates for reaching each stage of the
/// 2026 tournament, generated by simulating the entire tournament
/// [totalSimulations] times using pre-computed pairwise win probabilities.
class TournamentSimulationResult {
  /// Number of tournament simulations run.
  final int totalSimulations;

  /// Per-team simulation results keyed by team code.
  final Map<String, TeamSimulationResult> teamResults;

  /// When the simulation was generated.
  final DateTime generatedAt;

  /// Wall-clock duration of the simulation run.
  final Duration elapsed;

  const TournamentSimulationResult({
    required this.totalSimulations,
    required this.teamResults,
    required this.generatedAt,
    required this.elapsed,
  });

  /// Get teams sorted by tournament win probability (descending).
  List<TeamSimulationResult> get rankedByWinPct {
    final sorted = teamResults.values.toList()
      ..sort((a, b) => b.winnerPct.compareTo(a.winnerPct));
    return sorted;
  }

  /// Get teams sorted by probability of reaching a given stage (descending).
  List<TeamSimulationResult> rankedByStage(String stage) {
    final sorted = teamResults.values.toList()
      ..sort((a, b) {
        final bVal = _getStagePct(b, stage);
        final aVal = _getStagePct(a, stage);
        return bVal.compareTo(aVal);
      });
    return sorted;
  }

  double _getStagePct(TeamSimulationResult r, String stage) {
    switch (stage) {
      case 'groupWinner':
        return r.groupWinnerPct;
      case 'roundOf32':
        return r.roundOf32Pct;
      case 'roundOf16':
        return r.roundOf16Pct;
      case 'quarterFinal':
        return r.quarterFinalPct;
      case 'semiFinal':
        return r.semiFinalPct;
      case 'final':
        return r.finalPct;
      case 'winner':
        return r.winnerPct;
      default:
        return r.winnerPct;
    }
  }
}

/// Per-team simulation result with probabilities for each tournament stage.
class TeamSimulationResult {
  /// 3-letter team code (e.g. "BRA", "ARG").
  final String teamCode;

  /// Full country name.
  final String teamName;

  /// Percentage of simulations where the team was eliminated in groups.
  final double groupStageExitPct;

  /// Percentage of simulations where the team reached the Round of 32.
  final double roundOf32Pct;

  /// Percentage of simulations where the team reached the Round of 16.
  final double roundOf16Pct;

  /// Percentage of simulations where the team reached the Quarter-Finals.
  final double quarterFinalPct;

  /// Percentage of simulations where the team reached the Semi-Finals.
  final double semiFinalPct;

  /// Percentage of simulations where the team reached the Final.
  final double finalPct;

  /// Percentage of simulations where the team won the tournament.
  final double winnerPct;

  /// Percentage of simulations where the team finished 1st in their group.
  final double groupWinnerPct;

  /// Average group-stage points across all simulations.
  final double avgGroupPoints;

  const TeamSimulationResult({
    required this.teamCode,
    required this.teamName,
    required this.groupStageExitPct,
    required this.roundOf32Pct,
    required this.roundOf16Pct,
    required this.quarterFinalPct,
    required this.semiFinalPct,
    required this.finalPct,
    required this.winnerPct,
    required this.groupWinnerPct,
    required this.avgGroupPoints,
  });

  @override
  String toString() =>
      '$teamName ($teamCode): Win ${winnerPct.toStringAsFixed(1)}%, '
      'Final ${finalPct.toStringAsFixed(1)}%, '
      'SF ${semiFinalPct.toStringAsFixed(1)}%, '
      'QF ${quarterFinalPct.toStringAsFixed(1)}%, '
      'R16 ${roundOf16Pct.toStringAsFixed(1)}%, '
      'R32 ${roundOf32Pct.toStringAsFixed(1)}%, '
      'GroupExit ${groupStageExitPct.toStringAsFixed(1)}%';
}

/// Monte Carlo tournament simulation service for 2026 tournament.
///
/// Simulates the entire 48-team tournament thousands of times using
/// Elo-based pairwise win probabilities to estimate each team's chances
/// of reaching each round of the tournament.
///
/// The 2026 format:
///   - 12 groups of 4 teams (groups A through L)
///   - Top 2 from each group (24 teams) + 8 best 3rd-place teams = 32 in R32
///   - Then R16, QF, SF, 3rd-place, Final
///
/// Performance target: 10,000 simulations in under 10 seconds.
class MonteCarloSimulationService {
  /// Default number of simulations to run.
  static const int defaultSimulations = 10000;

  /// Pre-computed Elo ratings for all 48 teams, derived from world rankings.
  late final Map<String, double> _eloRatings;

  /// Group assignments: group letter -> list of team codes.
  late final Map<String, List<String>> _groups;

  /// Team name lookup by team code.
  late final Map<String, String> _teamNames;

  /// All teams indexed by team code.
  late final Map<String, NationalTeam> _teamsByCode;

  /// Match engine for simulating individual matches.
  late final SimulationMatchEngine _matchEngine;

  /// Bracket builder for constructing knockout brackets.
  late final SimulationBracketBuilder _bracketBuilder;

  bool _isInitialized = false;

  /// Initialize the service with team data.
  ///
  /// If [teams] is provided, those teams are used; otherwise the
  /// service falls back to [WorldCupMockData.teams].
  void initialize({List<NationalTeam>? teams}) {
    final teamList = teams ?? WorldCupMockData.teams;

    _teamsByCode = {for (final t in teamList) t.teamCode: t};
    _teamNames = {for (final t in teamList) t.teamCode: t.countryName};
    _eloRatings = {for (final t in teamList) t.teamCode: _rankingToElo(t.worldRanking ?? 50)};

    // Build group map from team data
    _groups = {};
    for (final t in teamList) {
      final group = t.group;
      if (group != null && group.isNotEmpty) {
        _groups.putIfAbsent(group, () => []).add(t.teamCode);
      }
    }

    // Initialize match engine and bracket builder
    _matchEngine = SimulationMatchEngine(_eloRatings);
    _bracketBuilder = SimulationBracketBuilder(
      _teamsByCode.keys.toSet(),
      _matchEngine,
    );

    _isInitialized = true;
  }

  /// Convert world ranking to an approximate Elo rating.
  ///
  /// Rank 1 -> ~2100, rank 50 -> ~1600, rank 100 -> ~1350, rank 200 -> ~1100.
  /// Uses a logarithmic curve to give more separation at the top end.
  static double _rankingToElo(int rank) {
    // Clamp rank to [1, 210]
    final r = rank.clamp(1, 210).toDouble();
    // Log curve: Elo = 2200 - 400 * ln(rank) / ln(50)
    // rank 1 -> 2200, rank 50 -> 1800, rank 130 -> ~1555
    return 2200.0 - 400.0 * math.log(r) / math.log(50);
  }

  /// Compute match probabilities between two teams.
  ///
  /// Returns a map with keys 'homeWin', 'draw', 'awayWin' representing
  /// the probabilities of each outcome.
  ///
  /// If [isKnockout] is true, the draw probability is reduced (since knockout
  /// matches are more likely to be decided in regulation).
  ///
  /// Delegates to the match engine for base computation.
  Map<String, double> computeMatchProbabilities(
    String teamACode,
    String teamBCode, {
    bool isKnockout = false,
  }) {
    if (!_isInitialized) {
      throw StateError('Service must be initialized before computing probabilities');
    }

    final probs = _matchEngine.computeMatchProbabilities(teamACode, teamBCode);

    var homeWin = probs['win']!;
    var draw = probs['draw']!;
    var awayWin = probs['loss']!;

    // Reduce draw probability for knockout matches
    if (isKnockout) {
      draw *= 0.4; // Reduce draw probability by 60%
      // Redistribute to win/loss proportionally
      final remaining = homeWin + awayWin;
      final redistribution = (probs['draw']! - draw);
      homeWin += redistribution * (homeWin / remaining);
      awayWin += redistribution * (awayWin / remaining);
    }

    // Renormalize to ensure sum = 1.0
    final total = homeWin + draw + awayWin;
    return {
      'homeWin': homeWin / total,
      'draw': draw / total,
      'awayWin': awayWin / total,
    };
  }


  /// Run a full Monte Carlo tournament simulation.
  ///
  /// [simulations] controls how many iterations to run (default 10,000).
  /// [teams] optionally overrides the team data (auto-initializes if needed).
  /// [seed] optionally sets a deterministic seed for reproducibility.
  ///
  /// Returns a [TournamentSimulationResult] with per-team stage probabilities.
  TournamentSimulationResult simulateTournament({
    int simulations = defaultSimulations,
    List<NationalTeam>? teams,
    int? seed,
  }) {
    if (!_isInitialized) {
      initialize(teams: teams);
    }

    final stopwatch = Stopwatch()..start();
    final rng = seed != null ? math.Random(seed) : math.Random();

    // Accumulators: teamCode -> counts
    final groupWinnerCount = <String, int>{};
    final reachedR32 = <String, int>{};
    final reachedR16 = <String, int>{};
    final reachedQF = <String, int>{};
    final reachedSF = <String, int>{};
    final reachedFinal = <String, int>{};
    final wonTournament = <String, int>{};
    final totalGroupPoints = <String, double>{};

    // Initialize accumulators
    for (final code in _teamsByCode.keys) {
      groupWinnerCount[code] = 0;
      reachedR32[code] = 0;
      reachedR16[code] = 0;
      reachedQF[code] = 0;
      reachedSF[code] = 0;
      reachedFinal[code] = 0;
      wonTournament[code] = 0;
      totalGroupPoints[code] = 0;
    }

    for (int sim = 0; sim < simulations; sim++) {
      _runSingleSimulation(
        rng: rng,
        groupWinnerCount: groupWinnerCount,
        reachedR32: reachedR32,
        reachedR16: reachedR16,
        reachedQF: reachedQF,
        reachedSF: reachedSF,
        reachedFinal: reachedFinal,
        wonTournament: wonTournament,
        totalGroupPoints: totalGroupPoints,
      );
    }

    stopwatch.stop();

    // Build results
    final teamResults = <String, TeamSimulationResult>{};
    for (final code in _teamsByCode.keys) {
      final r32 = reachedR32[code]!;
      final r16 = reachedR16[code]!;
      final qf = reachedQF[code]!;
      final sf = reachedSF[code]!;
      final fin = reachedFinal[code]!;
      final won = wonTournament[code]!;

      teamResults[code] = TeamSimulationResult(
        teamCode: code,
        teamName: _teamNames[code] ?? code,
        groupStageExitPct: ((simulations - r32) / simulations) * 100,
        roundOf32Pct: (r32 / simulations) * 100,
        roundOf16Pct: (r16 / simulations) * 100,
        quarterFinalPct: (qf / simulations) * 100,
        semiFinalPct: (sf / simulations) * 100,
        finalPct: (fin / simulations) * 100,
        winnerPct: (won / simulations) * 100,
        groupWinnerPct: (groupWinnerCount[code]! / simulations) * 100,
        avgGroupPoints: totalGroupPoints[code]! / simulations,
      );
    }

    return TournamentSimulationResult(
      totalSimulations: simulations,
      teamResults: teamResults,
      generatedAt: DateTime.now(),
      elapsed: stopwatch.elapsed,
    );
  }

  /// Run a single tournament simulation, updating all accumulator maps.
  void _runSingleSimulation({
    required math.Random rng,
    required Map<String, int> groupWinnerCount,
    required Map<String, int> reachedR32,
    required Map<String, int> reachedR16,
    required Map<String, int> reachedQF,
    required Map<String, int> reachedSF,
    required Map<String, int> reachedFinal,
    required Map<String, int> wonTournament,
    required Map<String, double> totalGroupPoints,
  }) {
    // --- Phase 1: Group Stage ---
    final groupStandings = _matchEngine.simulateGroupStage(_groups, rng);

    final groupWinners = <String, String>{};
    final groupRunners = <String, String>{};
    final thirdPlaceTeams = <ThirdPlaceEntry>[];

    for (final entry in groupStandings.entries) {
      final group = entry.key;
      final standings = entry.value;

      // Accumulate group points
      for (final standing in standings) {
        totalGroupPoints[standing.team] =
            (totalGroupPoints[standing.team] ?? 0) + standing.points;
      }

      // Top 2 advance, track 3rd for best 3rd-place
      if (standings.isNotEmpty) {
        groupWinners[group] = standings[0].team;
        groupWinnerCount[standings[0].team] =
            (groupWinnerCount[standings[0].team] ?? 0) + 1;
      }
      if (standings.length >= 2) {
        groupRunners[group] = standings[1].team;
      }
      if (standings.length >= 3) {
        thirdPlaceTeams.add(ThirdPlaceEntry(
          group: group,
          team: standings[2].team,
          points: standings[2].points,
          goalDiff: standings[2].goalDiff,
          goalsScored: standings[2].goalsScored,
        ));
      }
    }

    // --- Determine 8 best 3rd-place teams ---
    thirdPlaceTeams.sort((a, b) {
      if (a.points != b.points) return b.points.compareTo(a.points);
      if (a.goalDiff != b.goalDiff) return b.goalDiff.compareTo(a.goalDiff);
      return b.goalsScored.compareTo(a.goalsScored);
    });
    final qualifiedThirds = thirdPlaceTeams.take(8).toList();

    // All R32 qualifiers
    final r32Teams = <String>{};
    r32Teams.addAll(groupWinners.values);
    r32Teams.addAll(groupRunners.values);
    for (final t in qualifiedThirds) {
      r32Teams.add(t.team);
    }

    for (final code in r32Teams) {
      reachedR32[code] = (reachedR32[code] ?? 0) + 1;
    }

    // --- Phase 2: Round of 32 ---
    final r32Matchups = _bracketBuilder.buildR32Bracket(groupStandings);

    final r16Teams = <String>[];
    for (final matchup in r32Matchups) {
      final winner = _matchEngine.simulateKnockoutMatch(matchup[0], matchup[1], rng);
      r16Teams.add(winner);
    }

    for (final code in r16Teams) {
      reachedR16[code] = (reachedR16[code] ?? 0) + 1;
    }

    // --- Phase 3: Round of 16 ---
    if (r16Teams.length < 16) return;
    final qfTeams = <String>[];
    for (int i = 0; i < 16; i += 2) {
      final winner = _matchEngine.simulateKnockoutMatch(r16Teams[i], r16Teams[i + 1], rng);
      qfTeams.add(winner);
    }

    for (final code in qfTeams) {
      reachedQF[code] = (reachedQF[code] ?? 0) + 1;
    }

    // --- Phase 4: Quarter-Finals ---
    if (qfTeams.length < 8) return;
    final sfTeams = <String>[];
    for (int i = 0; i < 8; i += 2) {
      final winner = _matchEngine.simulateKnockoutMatch(qfTeams[i], qfTeams[i + 1], rng);
      sfTeams.add(winner);
    }

    for (final code in sfTeams) {
      reachedSF[code] = (reachedSF[code] ?? 0) + 1;
    }

    // --- Phase 5: Semi-Finals ---
    if (sfTeams.length < 4) return;
    final finalists = <String>[];
    for (int i = 0; i < 4; i += 2) {
      final winner = _matchEngine.simulateKnockoutMatch(sfTeams[i], sfTeams[i + 1], rng);
      finalists.add(winner);
    }

    for (final code in finalists) {
      reachedFinal[code] = (reachedFinal[code] ?? 0) + 1;
    }

    // --- Phase 6: Final ---
    if (finalists.length < 2) return;
    final champion = _matchEngine.simulateKnockoutMatch(finalists[0], finalists[1], rng);
    wonTournament[champion] = (wonTournament[champion] ?? 0) + 1;
  }


  /// Get the Elo rating for a team. Returns null if not initialized.
  double? getEloRating(String teamCode) {
    if (!_isInitialized) return null;
    return _eloRatings[teamCode];
  }

  /// Check if the service is initialized.
  bool get isInitialized => _isInitialized;
}
