import 'dart:math' as math;

import '../../domain/entities/entities.dart';
import '../mock/world_cup_mock_data.dart';

/// Result of a full tournament Monte Carlo simulation.
///
/// Contains per-team probability estimates for reaching each stage of the
/// FIFA World Cup 2026, generated by simulating the entire tournament
/// [totalSimulations] times using pre-computed pairwise win probabilities.
class TournamentSimulationResult {
  /// Number of tournament simulations run.
  final int totalSimulations;

  /// Per-team simulation results keyed by FIFA code.
  final Map<String, TeamSimulationResult> teamResults;

  /// When the simulation was generated.
  final DateTime generatedAt;

  /// Wall-clock duration of the simulation run.
  final Duration elapsed;

  const TournamentSimulationResult({
    required this.totalSimulations,
    required this.teamResults,
    required this.generatedAt,
    required this.elapsed,
  });

  /// Get teams sorted by tournament win probability (descending).
  List<TeamSimulationResult> get rankedByWinPct {
    final sorted = teamResults.values.toList()
      ..sort((a, b) => b.winnerPct.compareTo(a.winnerPct));
    return sorted;
  }

  /// Get teams sorted by probability of reaching a given stage (descending).
  List<TeamSimulationResult> rankedByStage(String stage) {
    final sorted = teamResults.values.toList()
      ..sort((a, b) {
        final bVal = _getStagePct(b, stage);
        final aVal = _getStagePct(a, stage);
        return bVal.compareTo(aVal);
      });
    return sorted;
  }

  double _getStagePct(TeamSimulationResult r, String stage) {
    switch (stage) {
      case 'groupWinner':
        return r.groupWinnerPct;
      case 'roundOf32':
        return r.roundOf32Pct;
      case 'roundOf16':
        return r.roundOf16Pct;
      case 'quarterFinal':
        return r.quarterFinalPct;
      case 'semiFinal':
        return r.semiFinalPct;
      case 'final':
        return r.finalPct;
      case 'winner':
        return r.winnerPct;
      default:
        return r.winnerPct;
    }
  }
}

/// Per-team simulation result with probabilities for each tournament stage.
class TeamSimulationResult {
  /// FIFA 3-letter code (e.g. "BRA", "ARG").
  final String teamCode;

  /// Full country name.
  final String teamName;

  /// Percentage of simulations where the team was eliminated in groups.
  final double groupStageExitPct;

  /// Percentage of simulations where the team reached the Round of 32.
  final double roundOf32Pct;

  /// Percentage of simulations where the team reached the Round of 16.
  final double roundOf16Pct;

  /// Percentage of simulations where the team reached the Quarter-Finals.
  final double quarterFinalPct;

  /// Percentage of simulations where the team reached the Semi-Finals.
  final double semiFinalPct;

  /// Percentage of simulations where the team reached the Final.
  final double finalPct;

  /// Percentage of simulations where the team won the tournament.
  final double winnerPct;

  /// Percentage of simulations where the team finished 1st in their group.
  final double groupWinnerPct;

  /// Average group-stage points across all simulations.
  final double avgGroupPoints;

  const TeamSimulationResult({
    required this.teamCode,
    required this.teamName,
    required this.groupStageExitPct,
    required this.roundOf32Pct,
    required this.roundOf16Pct,
    required this.quarterFinalPct,
    required this.semiFinalPct,
    required this.finalPct,
    required this.winnerPct,
    required this.groupWinnerPct,
    required this.avgGroupPoints,
  });

  @override
  String toString() =>
      '$teamName ($teamCode): Win ${winnerPct.toStringAsFixed(1)}%, '
      'Final ${finalPct.toStringAsFixed(1)}%, '
      'SF ${semiFinalPct.toStringAsFixed(1)}%, '
      'QF ${quarterFinalPct.toStringAsFixed(1)}%, '
      'R16 ${roundOf16Pct.toStringAsFixed(1)}%, '
      'R32 ${roundOf32Pct.toStringAsFixed(1)}%, '
      'GroupExit ${groupStageExitPct.toStringAsFixed(1)}%';
}

/// Monte Carlo tournament simulation service for FIFA World Cup 2026.
///
/// Simulates the entire 48-team tournament thousands of times using
/// Elo-based pairwise win probabilities to estimate each team's chances
/// of reaching each round of the tournament.
///
/// The 2026 format:
///   - 12 groups of 4 teams (groups A through L)
///   - Top 2 from each group (24 teams) + 8 best 3rd-place teams = 32 in R32
///   - Then R16, QF, SF, 3rd-place, Final
///
/// Performance target: 10,000 simulations in under 10 seconds.
class MonteCarloSimulationService {
  /// Default number of simulations to run.
  static const int defaultSimulations = 10000;

  /// Elo scaling factor. A 400-point difference gives ~91% win expectancy.
  static const double _eloK = 400.0;

  /// Base draw probability for group stage matches.
  static const double _baseDrawProb = 0.24;

  /// Home advantage boost (Elo points equivalent) for host nations.
  static const double _hostAdvantage = 60.0;

  /// Host nation FIFA codes for 2026.
  static const _hostNations = {'USA', 'MEX', 'CAN'};

  /// Pre-computed Elo ratings for all 48 teams, derived from FIFA rankings.
  late final Map<String, double> _eloRatings;

  /// Group assignments: group letter -> list of FIFA codes.
  late final Map<String, List<String>> _groups;

  /// Team name lookup by FIFA code.
  late final Map<String, String> _teamNames;

  /// All teams indexed by FIFA code.
  late final Map<String, NationalTeam> _teamsByCode;

  bool _isInitialized = false;

  /// Initialize the service with team data.
  ///
  /// If [teams] is provided, those teams are used; otherwise the
  /// service falls back to [WorldCupMockData.teams].
  void initialize({List<NationalTeam>? teams}) {
    final teamList = teams ?? WorldCupMockData.teams;

    _teamsByCode = {for (final t in teamList) t.fifaCode: t};
    _teamNames = {for (final t in teamList) t.fifaCode: t.countryName};
    _eloRatings = {for (final t in teamList) t.fifaCode: _rankingToElo(t.fifaRanking ?? 50)};

    // Build group map from team data
    _groups = {};
    for (final t in teamList) {
      final group = t.group;
      if (group != null && group.isNotEmpty) {
        _groups.putIfAbsent(group, () => []).add(t.fifaCode);
      }
    }

    _isInitialized = true;
  }

  /// Convert FIFA ranking to an approximate Elo rating.
  ///
  /// Rank 1 -> ~2100, rank 50 -> ~1600, rank 100 -> ~1350, rank 200 -> ~1100.
  /// Uses a logarithmic curve to give more separation at the top end.
  static double _rankingToElo(int rank) {
    // Clamp rank to [1, 210]
    final r = rank.clamp(1, 210).toDouble();
    // Log curve: Elo = 2200 - 400 * ln(rank) / ln(50)
    // rank 1 -> 2200, rank 50 -> 1800, rank 130 -> ~1555
    return 2200.0 - 400.0 * math.log(r) / math.log(50);
  }

  /// Compute the expected win probability for teamA vs teamB using Elo.
  ///
  /// Returns a map with keys 'homeWin', 'draw', 'awayWin' summing to 1.0.
  /// [isKnockout] reduces draw probability (draws resolved via penalties).
  Map<String, double> computeMatchProbabilities(
    String teamACode,
    String teamBCode, {
    bool isKnockout = false,
  }) {
    final eloA = _eloRatings[teamACode] ?? 1500.0;
    final eloB = _eloRatings[teamBCode] ?? 1500.0;

    // Apply host advantage
    final adjustedA = eloA + (_hostNations.contains(teamACode) ? _hostAdvantage : 0);
    final adjustedB = eloB + (_hostNations.contains(teamBCode) ? _hostAdvantage : 0);

    // Standard Elo expected score
    final diff = adjustedA - adjustedB;
    final expectedA = 1.0 / (1.0 + math.pow(10, -diff / _eloK));

    // Split into win/draw/away using the draw bridge model
    double drawProb = _baseDrawProb * (1.0 - 0.5 * (expectedA - 0.5).abs());
    if (isKnockout) {
      drawProb *= 0.4; // Knockouts rarely go to penalties in simulation terms
    }
    drawProb = drawProb.clamp(0.03, 0.35);

    var homeWin = expectedA - drawProb / 2.0;
    var awayWin = (1.0 - expectedA) - drawProb / 2.0;

    // Clamp and renormalize
    homeWin = homeWin.clamp(0.03, 0.94);
    awayWin = awayWin.clamp(0.03, 0.94);
    drawProb = drawProb.clamp(0.03, 0.94);

    final total = homeWin + drawProb + awayWin;
    return {
      'homeWin': homeWin / total,
      'draw': drawProb / total,
      'awayWin': awayWin / total,
    };
  }

  /// Run a full Monte Carlo tournament simulation.
  ///
  /// [simulations] controls how many iterations to run (default 10,000).
  /// [teams] optionally overrides the team data (auto-initializes if needed).
  /// [seed] optionally sets a deterministic seed for reproducibility.
  ///
  /// Returns a [TournamentSimulationResult] with per-team stage probabilities.
  TournamentSimulationResult simulateTournament({
    int simulations = defaultSimulations,
    List<NationalTeam>? teams,
    int? seed,
  }) {
    if (!_isInitialized) {
      initialize(teams: teams);
    }

    final stopwatch = Stopwatch()..start();
    final rng = seed != null ? math.Random(seed) : math.Random();

    // Accumulators: teamCode -> counts
    final groupWinnerCount = <String, int>{};
    final reachedR32 = <String, int>{};
    final reachedR16 = <String, int>{};
    final reachedQF = <String, int>{};
    final reachedSF = <String, int>{};
    final reachedFinal = <String, int>{};
    final wonTournament = <String, int>{};
    final totalGroupPoints = <String, double>{};

    // Initialize accumulators
    for (final code in _teamsByCode.keys) {
      groupWinnerCount[code] = 0;
      reachedR32[code] = 0;
      reachedR16[code] = 0;
      reachedQF[code] = 0;
      reachedSF[code] = 0;
      reachedFinal[code] = 0;
      wonTournament[code] = 0;
      totalGroupPoints[code] = 0;
    }

    // Pre-compute all pairwise probabilities for efficiency
    final pairwiseProbs = _precomputePairwiseProbs();

    for (int sim = 0; sim < simulations; sim++) {
      _runSingleSimulation(
        rng: rng,
        pairwiseProbs: pairwiseProbs,
        groupWinnerCount: groupWinnerCount,
        reachedR32: reachedR32,
        reachedR16: reachedR16,
        reachedQF: reachedQF,
        reachedSF: reachedSF,
        reachedFinal: reachedFinal,
        wonTournament: wonTournament,
        totalGroupPoints: totalGroupPoints,
      );
    }

    stopwatch.stop();

    // Build results
    final teamResults = <String, TeamSimulationResult>{};
    for (final code in _teamsByCode.keys) {
      final r32 = reachedR32[code]!;
      final r16 = reachedR16[code]!;
      final qf = reachedQF[code]!;
      final sf = reachedSF[code]!;
      final fin = reachedFinal[code]!;
      final won = wonTournament[code]!;

      teamResults[code] = TeamSimulationResult(
        teamCode: code,
        teamName: _teamNames[code] ?? code,
        groupStageExitPct: ((simulations - r32) / simulations) * 100,
        roundOf32Pct: (r32 / simulations) * 100,
        roundOf16Pct: (r16 / simulations) * 100,
        quarterFinalPct: (qf / simulations) * 100,
        semiFinalPct: (sf / simulations) * 100,
        finalPct: (fin / simulations) * 100,
        winnerPct: (won / simulations) * 100,
        groupWinnerPct: (groupWinnerCount[code]! / simulations) * 100,
        avgGroupPoints: totalGroupPoints[code]! / simulations,
      );
    }

    return TournamentSimulationResult(
      totalSimulations: simulations,
      teamResults: teamResults,
      generatedAt: DateTime.now(),
      elapsed: stopwatch.elapsed,
    );
  }

  /// Pre-compute win/draw/loss probabilities for every possible team pairing.
  ///
  /// Returns a nested map: pairwiseProbs[teamA][teamB] = {'homeWin', 'draw', 'awayWin'}.
  /// Both orderings are stored for O(1) lookup during simulation.
  Map<String, Map<String, Map<String, double>>> _precomputePairwiseProbs() {
    final codes = _teamsByCode.keys.toList();
    final result = <String, Map<String, Map<String, double>>>{};

    for (final code in codes) {
      result[code] = {};
    }

    for (int i = 0; i < codes.length; i++) {
      for (int j = i + 1; j < codes.length; j++) {
        final a = codes[i];
        final b = codes[j];

        // Group stage probabilities (with draws)
        final groupProbs = computeMatchProbabilities(a, b, isKnockout: false);
        result[a]![b] = groupProbs;
        // Reverse for b vs a
        result[b]![a] = {
          'homeWin': groupProbs['awayWin']!,
          'draw': groupProbs['draw']!,
          'awayWin': groupProbs['homeWin']!,
        };
      }
    }

    return result;
  }

  /// Run a single tournament simulation, updating all accumulator maps.
  void _runSingleSimulation({
    required math.Random rng,
    required Map<String, Map<String, Map<String, double>>> pairwiseProbs,
    required Map<String, int> groupWinnerCount,
    required Map<String, int> reachedR32,
    required Map<String, int> reachedR16,
    required Map<String, int> reachedQF,
    required Map<String, int> reachedSF,
    required Map<String, int> reachedFinal,
    required Map<String, int> wonTournament,
    required Map<String, double> totalGroupPoints,
  }) {
    // --- Phase 1: Group Stage ---
    final groupWinners = <String, String>{}; // group -> 1st place code
    final groupRunners = <String, String>{}; // group -> 2nd place code
    final thirdPlaceTeams = <_ThirdPlaceEntry>[];

    for (final entry in _groups.entries) {
      final group = entry.key;
      final teamCodes = entry.value;
      if (teamCodes.length < 2) continue;

      final standings = _simulateGroupStage(teamCodes, rng, pairwiseProbs);

      // Accumulate group points
      for (final standing in standings) {
        totalGroupPoints[standing.code] =
            (totalGroupPoints[standing.code] ?? 0) + standing.points;
      }

      // Top 2 advance, track 3rd for best 3rd-place
      if (standings.isNotEmpty) {
        groupWinners[group] = standings[0].code;
        groupWinnerCount[standings[0].code] =
            (groupWinnerCount[standings[0].code] ?? 0) + 1;
      }
      if (standings.length >= 2) {
        groupRunners[group] = standings[1].code;
      }
      if (standings.length >= 3) {
        thirdPlaceTeams.add(_ThirdPlaceEntry(
          code: standings[2].code,
          group: group,
          points: standings[2].points,
          goalDifference: standings[2].goalDifference,
          goalsFor: standings[2].goalsFor,
        ));
      }
    }

    // --- Determine 8 best 3rd-place teams ---
    thirdPlaceTeams.sort((a, b) {
      // Sort by points desc, then GD desc, then GF desc
      final ptsDiff = b.points.compareTo(a.points);
      if (ptsDiff != 0) return ptsDiff;
      final gdDiff = b.goalDifference.compareTo(a.goalDifference);
      if (gdDiff != 0) return gdDiff;
      return b.goalsFor.compareTo(a.goalsFor);
    });
    final qualifiedThirds = thirdPlaceTeams.take(8).toList();

    // All R32 qualifiers
    final r32Teams = <String>{};
    r32Teams.addAll(groupWinners.values);
    r32Teams.addAll(groupRunners.values);
    for (final t in qualifiedThirds) {
      r32Teams.add(t.code);
    }

    for (final code in r32Teams) {
      reachedR32[code] = (reachedR32[code] ?? 0) + 1;
    }

    // --- Phase 2: Round of 32 ---
    // Build R32 bracket: 16 matches
    // FIFA bracket structure for 2026 with 48 teams:
    //   Match 1: 1A vs 3C/D/E    Match 9:  1E vs 3A/B/F
    //   Match 2: 2C vs 2D        Match 10: 2A vs 2B
    //   Match 3: 1B vs 3A/E/F    Match 11: 1F vs 3B/C/D
    //   Match 4: 2E vs 2F        Match 12: 2G vs 2H
    //   Match 5: 1C vs 3B/G/H    Match 13: 1G vs 3E/F/I
    //   Match 6: 2I vs 2J        Match 14: 2K vs 2L
    //   Match 7: 1D vs 3F/I/J    Match 15: 1H vs 3G/J/K
    //   Match 8: 2K vs 2L        Match 16: 1I vs 3H/K/L
    //
    // Simplified: pair group winners with best 3rd-place teams from specific
    // groups, and runners-up face each other. For simulation purposes, we use
    // a deterministic bracket that respects the FIFA pairing principles.
    final r32Matchups = _buildR32Bracket(
      groupWinners: groupWinners,
      groupRunners: groupRunners,
      qualifiedThirds: qualifiedThirds,
    );

    final r16Teams = <String>[];
    for (final matchup in r32Matchups) {
      final winner = _simulateKnockoutMatch(
        matchup[0], matchup[1], rng, pairwiseProbs,
      );
      r16Teams.add(winner);
    }

    for (final code in r16Teams) {
      reachedR16[code] = (reachedR16[code] ?? 0) + 1;
    }

    // --- Phase 3: Round of 16 ---
    if (r16Teams.length < 16) return;
    final qfTeams = <String>[];
    for (int i = 0; i < 16; i += 2) {
      final winner = _simulateKnockoutMatch(
        r16Teams[i], r16Teams[i + 1], rng, pairwiseProbs,
      );
      qfTeams.add(winner);
    }

    for (final code in qfTeams) {
      reachedQF[code] = (reachedQF[code] ?? 0) + 1;
    }

    // --- Phase 4: Quarter-Finals ---
    if (qfTeams.length < 8) return;
    final sfTeams = <String>[];
    for (int i = 0; i < 8; i += 2) {
      final winner = _simulateKnockoutMatch(
        qfTeams[i], qfTeams[i + 1], rng, pairwiseProbs,
      );
      sfTeams.add(winner);
    }

    for (final code in sfTeams) {
      reachedSF[code] = (reachedSF[code] ?? 0) + 1;
    }

    // --- Phase 5: Semi-Finals ---
    if (sfTeams.length < 4) return;
    final finalists = <String>[];
    for (int i = 0; i < 4; i += 2) {
      final winner = _simulateKnockoutMatch(
        sfTeams[i], sfTeams[i + 1], rng, pairwiseProbs,
      );
      finalists.add(winner);
    }

    for (final code in finalists) {
      reachedFinal[code] = (reachedFinal[code] ?? 0) + 1;
    }

    // --- Phase 6: Final ---
    if (finalists.length < 2) return;
    final champion = _simulateKnockoutMatch(
      finalists[0], finalists[1], rng, pairwiseProbs,
    );
    wonTournament[champion] = (wonTournament[champion] ?? 0) + 1;
  }

  /// Simulate the group stage for a set of teams.
  ///
  /// Each team plays every other team once (round-robin). Returns standings
  /// sorted by points, then goal difference, then goals scored.
  List<_GroupStanding> _simulateGroupStage(
    List<String> teamCodes,
    math.Random rng,
    Map<String, Map<String, Map<String, double>>> pairwiseProbs,
  ) {
    final standings = <String, _GroupStanding>{};
    for (final code in teamCodes) {
      standings[code] = _GroupStanding(code: code);
    }

    // Round-robin: each pair plays once
    for (int i = 0; i < teamCodes.length; i++) {
      for (int j = i + 1; j < teamCodes.length; j++) {
        final home = teamCodes[i];
        final away = teamCodes[j];

        final probs = pairwiseProbs[home]?[away];
        if (probs == null) continue;

        final roll = rng.nextDouble();
        final homeWinProb = probs['homeWin']!;
        final drawProb = probs['draw']!;

        if (roll < homeWinProb) {
          // Home win
          final goals = _simulateGoals(rng, isWinner: true);
          final loserGoals = _simulateGoals(rng, isWinner: false);
          final homeGoals = math.max(goals, loserGoals + 1);
          standings[home]!.addResult(3, homeGoals, loserGoals);
          standings[away]!.addResult(0, loserGoals, homeGoals);
        } else if (roll < homeWinProb + drawProb) {
          // Draw
          final goals = _simulateGoals(rng, isDraw: true);
          standings[home]!.addResult(1, goals, goals);
          standings[away]!.addResult(1, goals, goals);
        } else {
          // Away win
          final goals = _simulateGoals(rng, isWinner: true);
          final loserGoals = _simulateGoals(rng, isWinner: false);
          final awayGoals = math.max(goals, loserGoals + 1);
          standings[away]!.addResult(3, awayGoals, loserGoals);
          standings[home]!.addResult(0, loserGoals, awayGoals);
        }
      }
    }

    // Sort standings
    final sorted = standings.values.toList();
    sorted.sort((a, b) {
      // 1. Points descending
      final ptsDiff = b.points.compareTo(a.points);
      if (ptsDiff != 0) return ptsDiff;
      // 2. Goal difference descending
      final gdDiff = b.goalDifference.compareTo(a.goalDifference);
      if (gdDiff != 0) return gdDiff;
      // 3. Goals scored descending
      final gfDiff = b.goalsFor.compareTo(a.goalsFor);
      if (gfDiff != 0) return gfDiff;
      // 4. Random tiebreaker (simulates drawing of lots)
      return rng.nextBool() ? 1 : -1;
    });

    return sorted;
  }

  /// Simulate a knockout match between two teams. Always produces a winner.
  ///
  /// If the Elo model draws, a weighted coin flip decides (favoring the
  /// stronger team, simulating extra time / penalties).
  String _simulateKnockoutMatch(
    String teamA,
    String teamB,
    math.Random rng,
    Map<String, Map<String, Map<String, double>>> pairwiseProbs,
  ) {
    final probs = pairwiseProbs[teamA]?[teamB];
    if (probs == null) {
      // Fallback: coin flip
      return rng.nextBool() ? teamA : teamB;
    }

    final homeWin = probs['homeWin']!;
    final drawProb = probs['draw']!;
    final roll = rng.nextDouble();

    if (roll < homeWin) {
      return teamA;
    } else if (roll < homeWin + drawProb) {
      // Draw in regulation -> extra time / penalties
      // Weighted coin flip: stronger team slightly favored
      final eloA = _eloRatings[teamA] ?? 1500.0;
      final eloB = _eloRatings[teamB] ?? 1500.0;
      // In penalties, advantage is smaller (60/40 rather than full Elo edge)
      final penaltyAdvA = 1.0 / (1.0 + math.pow(10, -(eloA - eloB) / 800.0));
      return rng.nextDouble() < penaltyAdvA ? teamA : teamB;
    } else {
      return teamB;
    }
  }

  /// Generate a plausible goal count for a team in a group match.
  int _simulateGoals(math.Random rng, {bool isWinner = false, bool isDraw = false}) {
    if (isDraw) {
      // Draw goals: 0, 1, or 2 (heavily weighted toward 0-1)
      final roll = rng.nextDouble();
      if (roll < 0.25) return 0;
      if (roll < 0.65) return 1;
      if (roll < 0.90) return 2;
      return 3;
    }
    if (isWinner) {
      // Winner goals: 1-4
      final roll = rng.nextDouble();
      if (roll < 0.40) return 1;
      if (roll < 0.75) return 2;
      if (roll < 0.92) return 3;
      return 4;
    }
    // Loser goals: 0-2
    final roll = rng.nextDouble();
    if (roll < 0.50) return 0;
    if (roll < 0.85) return 1;
    return 2;
  }

  /// Build the Round of 32 bracket matchups.
  ///
  /// Uses a simplified but realistic FIFA-style bracket: group winners face
  /// 3rd-place qualifiers, runners-up face each other. The bracket structure
  /// ensures teams from the same group cannot meet until the Quarter-Finals.
  List<List<String>> _buildR32Bracket({
    required Map<String, String> groupWinners,
    required Map<String, String> groupRunners,
    required List<_ThirdPlaceEntry> qualifiedThirds,
  }) {
    // Map qualified thirds by group for assignment
    final thirdsByGroup = <String, String>{};
    for (final t in qualifiedThirds) {
      thirdsByGroup[t.group] = t.code;
    }

    // Build matchups: 16 R32 matches
    // Structure: Group winners (1st) vs 3rd-place from designated groups,
    //            Group runners (2nd) vs 2nd-place from other groups
    //
    // FIFA bracket for 2026 (simplified mapping):
    // Upper half of bracket:
    //   1A vs best available 3rd   |   2C vs 2D
    //   1B vs best available 3rd   |   2E vs 2F
    //   1C vs best available 3rd   |   2A vs 2B
    //   1D vs best available 3rd   |   2G vs 2H
    // Lower half of bracket:
    //   1E vs best available 3rd   |   2I vs 2J
    //   1F vs best available 3rd   |   2K vs 2L
    //   1G vs best available 3rd   |   1I vs best available 3rd
    //   1H vs best available 3rd   |   1J vs best available 3rd
    //
    // NOTE: With 12 group winners and only 8 thirds, some winners face runners
    // instead. For simulation purposes, we use a deterministic pattern.

    final matchups = <List<String>>[];
    final groupLetters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L'];

    // Assign group winners to 3rd-place opponents
    // Winners from groups A-H get paired with available 3rd-place teams
    final availableThirds = List<String>.from(qualifiedThirds.map((t) => t.code));

    // 8 matches: group winner vs 3rd-place
    for (int i = 0; i < math.min(groupLetters.length, 8 + availableThirds.length); i++) {
      if (i < groupLetters.length && availableThirds.isNotEmpty) {
        final winner = groupWinners[groupLetters[i]];
        if (winner != null && i < 8) {
          // First 8 group winners pair with 3rd-place teams
          final third = availableThirds.removeAt(0);
          matchups.add([winner, third]);
        }
      }
    }

    // 4 remaining group winners pair with runners from specific groups
    // 1I vs 2H, 1J vs 2G, 1K vs 2J, 1L vs 2I
    final winnerRunnerPairs = [
      ['I', 'H'],
      ['J', 'G'],
      ['K', 'J'],
      ['L', 'I'],
    ];
    for (final pair in winnerRunnerPairs) {
      final winner = groupWinners[pair[0]];
      final runner = groupRunners[pair[1]];
      if (winner != null && runner != null) {
        matchups.add([winner, runner]);
      }
    }

    // Runner-up vs runner-up matches (4 matches)
    final runnerPairs = [
      ['A', 'B'],
      ['C', 'D'],
      ['E', 'F'],
      ['K', 'L'],
    ];
    for (final pair in runnerPairs) {
      final runner1 = groupRunners[pair[0]];
      final runner2 = groupRunners[pair[1]];
      if (runner1 != null && runner2 != null) {
        matchups.add([runner1, runner2]);
      }
    }

    // Ensure we have exactly 16 matchups; pad with any missing teams
    // This handles edge cases where groups might be incomplete
    while (matchups.length < 16) {
      // Fill with dummy matchups from remaining R32 teams
      final usedTeams = <String>{};
      for (final m in matchups) {
        usedTeams.addAll(m);
      }
      final remaining = _teamsByCode.keys.where((c) => !usedTeams.contains(c)).toList();
      if (remaining.length >= 2) {
        matchups.add([remaining[0], remaining[1]]);
      } else {
        break;
      }
    }

    return matchups;
  }

  /// Get the Elo rating for a team. Returns null if not initialized.
  double? getEloRating(String teamCode) {
    if (!_isInitialized) return null;
    return _eloRatings[teamCode];
  }

  /// Check if the service is initialized.
  bool get isInitialized => _isInitialized;
}

/// Internal helper for tracking group standings during simulation.
class _GroupStanding {
  final String code;
  int points = 0;
  int goalsFor = 0;
  int goalsAgainst = 0;

  _GroupStanding({required this.code});

  int get goalDifference => goalsFor - goalsAgainst;

  void addResult(int pts, int gf, int ga) {
    points += pts;
    goalsFor += gf;
    goalsAgainst += ga;
  }
}

/// Internal helper for tracking 3rd-place teams across groups.
class _ThirdPlaceEntry {
  final String code;
  final String group;
  final int points;
  final int goalDifference;
  final int goalsFor;

  const _ThirdPlaceEntry({
    required this.code,
    required this.group,
    required this.points,
    required this.goalDifference,
    required this.goalsFor,
  });
}
