// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmi4yeleQW3Oi-6VGmn7NPhpCYu88F4JM',
    appId: '1:942034010384:web:fecbfbbdc8a0465b99a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    authDomain: 'pregame-b089e.firebaseapp.com',
    storageBucket: 'pregame-b089e.firebasestorage.app',
    measurementId: 'G-WEY5DQ2XV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJekX1uke82tjvL27uTvWUdirs_DQviWM',
    appId: '1:942034010384:android:3993b21444e45b1399a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    storageBucket: 'pregame-b089e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIVosiN2D9ytbwhF2_03RjdcfN7i_AIA',
    appId: '1:942034010384:ios:c3264211ef6ee5a799a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    storageBucket: 'pregame-b089e.firebasestorage.app',
    iosBundleId: 'com.christophercampbell.pregame',
  );

}