/// Pre-defined World Cup 2026 venue data.
///
/// Contains static venue definitions for all 16 host stadiums.
library;

import 'world_cup_venue.dart';

/// Pre-defined World Cup 2026 venues
class WorldCupVenues {
  static const List<WorldCupVenue> all = [
    // United States venues
    WorldCupVenue(
      venueId: 'metlife',
      name: 'MetLife Stadium',
      worldCupName: 'New York New Jersey Stadium',
      city: 'East Rutherford',
      state: 'New Jersey',
      country: HostCountry.usa,
      capacity: 82500,
      yearOpened: 2010,
      latitude: 40.8128,
      longitude: -74.0742,
      timeZone: 'America/New_York',
      utcOffset: -5,
      homeTeams: ['New York Giants', 'New York Jets'],
      sports: ['American Football'],
      hasRoof: false,
      keyMatches: ['Final'],
      matchCount: 8,
    ),
    WorldCupVenue(
      venueId: 'sofi',
      name: 'SoFi Stadium',
      city: 'Inglewood',
      state: 'California',
      country: HostCountry.usa,
      capacity: 70000,
      yearOpened: 2020,
      latitude: 33.9534,
      longitude: -118.3390,
      timeZone: 'America/Los_Angeles',
      utcOffset: -8,
      homeTeams: ['Los Angeles Rams', 'Los Angeles Chargers'],
      sports: ['American Football'],
      hasRoof: true,
      retractableRoof: true,
      keyMatches: ['Quarter-Final'],
      matchCount: 7,
    ),
    WorldCupVenue(
      venueId: 'att',
      name: 'AT&T Stadium',
      city: 'Arlington',
      state: 'Texas',
      country: HostCountry.usa,
      capacity: 80000,
      worldCupCapacity: 92000,
      yearOpened: 2009,
      latitude: 32.7473,
      longitude: -97.0945,
      timeZone: 'America/Chicago',
      utcOffset: -6,
      homeTeams: ['Dallas Cowboys'],
      sports: ['American Football'],
      hasRoof: true,
      retractableRoof: true,
      keyMatches: ['Semi-Final'],
      matchCount: 9,
    ),
    WorldCupVenue(
      venueId: 'mercedes_benz',
      name: 'Mercedes-Benz Stadium',
      city: 'Atlanta',
      state: 'Georgia',
      country: HostCountry.usa,
      capacity: 71000,
      yearOpened: 2017,
      latitude: 33.7553,
      longitude: -84.4006,
      timeZone: 'America/New_York',
      utcOffset: -5,
      homeTeams: ['Atlanta Falcons', 'Atlanta United'],
      sports: ['American Football', 'Soccer'],
      hasRoof: true,
      retractableRoof: true,
      keyMatches: ['Semi-Final'],
      matchCount: 7,
    ),
    WorldCupVenue(
      venueId: 'hard_rock',
      name: 'Hard Rock Stadium',
      city: 'Miami Gardens',
      state: 'Florida',
      country: HostCountry.usa,
      capacity: 65000,
      yearOpened: 1987,
      latitude: 25.9580,
      longitude: -80.2389,
      timeZone: 'America/New_York',
      utcOffset: -5,
      homeTeams: ['Miami Dolphins', 'Inter Miami CF'],
      sports: ['American Football', 'Soccer'],
      hasRoof: false,
      matchCount: 7,
    ),
    WorldCupVenue(
      venueId: 'nrg',
      name: 'NRG Stadium',
      city: 'Houston',
      state: 'Texas',
      country: HostCountry.usa,
      capacity: 72000,
      yearOpened: 2002,
      latitude: 29.6847,
      longitude: -95.4107,
      timeZone: 'America/Chicago',
      utcOffset: -6,
      homeTeams: ['Houston Texans'],
      sports: ['American Football'],
      hasRoof: true,
      retractableRoof: true,
      matchCount: 5,
    ),
    WorldCupVenue(
      venueId: 'lincoln_financial',
      name: 'Lincoln Financial Field',
      city: 'Philadelphia',
      state: 'Pennsylvania',
      country: HostCountry.usa,
      capacity: 69000,
      yearOpened: 2003,
      latitude: 39.9008,
      longitude: -75.1675,
      timeZone: 'America/New_York',
      utcOffset: -5,
      homeTeams: ['Philadelphia Eagles'],
      sports: ['American Football'],
      hasRoof: false,
      matchCount: 6,
    ),
    WorldCupVenue(
      venueId: 'lumen',
      name: 'Lumen Field',
      city: 'Seattle',
      state: 'Washington',
      country: HostCountry.usa,
      capacity: 69000,
      yearOpened: 2002,
      latitude: 47.5952,
      longitude: -122.3316,
      timeZone: 'America/Los_Angeles',
      utcOffset: -8,
      homeTeams: ['Seattle Seahawks', 'Seattle Sounders'],
      sports: ['American Football', 'Soccer'],
      hasRoof: false,
      matchCount: 6,
    ),
    WorldCupVenue(
      venueId: 'levis',
      name: "Levi's Stadium",
      city: 'Santa Clara',
      state: 'California',
      country: HostCountry.usa,
      capacity: 68500,
      yearOpened: 2014,
      latitude: 37.4033,
      longitude: -121.9695,
      timeZone: 'America/Los_Angeles',
      utcOffset: -8,
      homeTeams: ['San Francisco 49ers'],
      sports: ['American Football'],
      hasRoof: false,
      matchCount: 6,
    ),
    WorldCupVenue(
      venueId: 'gillette',
      name: 'Gillette Stadium',
      city: 'Foxborough',
      state: 'Massachusetts',
      country: HostCountry.usa,
      capacity: 65000,
      yearOpened: 2002,
      latitude: 42.0909,
      longitude: -71.2643,
      timeZone: 'America/New_York',
      utcOffset: -5,
      homeTeams: ['New England Patriots', 'New England Revolution'],
      sports: ['American Football', 'Soccer'],
      hasRoof: false,
      matchCount: 6,
    ),
    WorldCupVenue(
      venueId: 'arrowhead',
      name: 'GEHA Field at Arrowhead Stadium',
      city: 'Kansas City',
      state: 'Missouri',
      country: HostCountry.usa,
      capacity: 76000,
      yearOpened: 1972,
      latitude: 39.0489,
      longitude: -94.4839,
      timeZone: 'America/Chicago',
      utcOffset: -6,
      homeTeams: ['Kansas City Chiefs'],
      sports: ['American Football'],
      hasRoof: false,
      matchCount: 6,
    ),
    // Mexico venues
    WorldCupVenue(
      venueId: 'azteca',
      name: 'Estadio Azteca',
      city: 'Mexico City',
      country: HostCountry.mexico,
      capacity: 87000,
      worldCupCapacity: 90000,
      yearOpened: 1966,
      latitude: 19.3029,
      longitude: -99.1506,
      timeZone: 'America/Mexico_City',
      utcOffset: -6,
      homeTeams: ['Club Am\u00e9rica', 'Cruz Azul', 'Mexico National Team'],
      sports: ['Soccer'],
      hasRoof: false,
      keyMatches: ['Opening Match'],
      matchCount: 6,
      description: 'Only stadium to host 3 World Cup tournaments (1970, 1986, 2026)',
    ),
    WorldCupVenue(
      venueId: 'akron',
      name: 'Estadio Akron',
      city: 'Guadalajara',
      state: 'Jalisco',
      country: HostCountry.mexico,
      capacity: 49850,
      yearOpened: 2010,
      latitude: 20.6821,
      longitude: -103.4621,
      timeZone: 'America/Mexico_City',
      utcOffset: -6,
      homeTeams: ['C.D. Guadalajara (Chivas)'],
      sports: ['Soccer'],
      hasRoof: false,
      matchCount: 5,
    ),
    WorldCupVenue(
      venueId: 'bbva',
      name: 'Estadio BBVA',
      city: 'Monterrey',
      state: 'Nuevo Le\u00f3n',
      country: HostCountry.mexico,
      capacity: 53500,
      yearOpened: 2015,
      latitude: 25.6703,
      longitude: -100.2438,
      timeZone: 'America/Monterrey',
      utcOffset: -6,
      homeTeams: ['C.F. Monterrey'],
      sports: ['Soccer'],
      hasRoof: false,
      matchCount: 5,
    ),
    // Canada venues
    WorldCupVenue(
      venueId: 'bmo',
      name: 'BMO Field',
      city: 'Toronto',
      state: 'Ontario',
      country: HostCountry.canada,
      capacity: 45500,
      yearOpened: 2007,
      latitude: 43.6332,
      longitude: -79.4186,
      timeZone: 'America/Toronto',
      utcOffset: -5,
      homeTeams: ['Toronto FC', 'Toronto Argonauts'],
      sports: ['Soccer', 'Canadian Football'],
      hasRoof: false,
      keyMatches: ['Canada Opening Match'],
      matchCount: 6,
    ),
    WorldCupVenue(
      venueId: 'bc_place',
      name: 'BC Place',
      city: 'Vancouver',
      state: 'British Columbia',
      country: HostCountry.canada,
      capacity: 54500,
      yearOpened: 1983,
      latitude: 49.2768,
      longitude: -123.1119,
      timeZone: 'America/Vancouver',
      utcOffset: -8,
      homeTeams: ['Vancouver Whitecaps', 'BC Lions'],
      sports: ['Soccer', 'Canadian Football'],
      hasRoof: true,
      retractableRoof: true,
      matchCount: 6,
    ),
  ];

  /// Get venue by ID
  static WorldCupVenue? getById(String venueId) {
    try {
      return all.firstWhere((v) => v.venueId == venueId);
    } catch (_) {
      return null;
    }
  }

  /// Get venues by country
  static List<WorldCupVenue> getByCountry(HostCountry country) {
    return all.where((v) => v.country == country).toList();
  }

  /// Get venues with key matches
  static List<WorldCupVenue> getKeyMatchVenues() {
    return all.where((v) => v.hasKeyMatch).toList();
  }
}
