// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Updated with actual values for the project pregame-b089e
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn0OJlJ_g28glzHKnrVUguG-u972oGEPg',
    appId: '1:942034010384:web:ef961549dd4272f2694674',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    authDomain: 'pregame-b089e.firebaseapp.com',
    storageBucket: 'pregame-b089e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJekX1uke82tjvL27uTvWUdirs_DQviWM',
    appId: '1:942034010384:android:df98b6a3914817b299a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    storageBucket: 'pregame-b089e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIVosiN2D9ytbwhF2_03RjdcfN7i_AIA',
    appId: '1:942034010384:ios:3f7b887b3877f14e99a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    storageBucket: 'pregame-b089e.firebasestorage.app',
    iosBundleId: 'com.christophercampbell.pregameworldcup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXIVosiN2D9ytbwhF2_03RjdcfN7i_AIA',
    appId: '1:942034010384:ios:3f7b887b3877f14e99a595',
    messagingSenderId: '942034010384',
    projectId: 'pregame-b089e',
    storageBucket: 'pregame-b089e.firebasestorage.app',
    iosBundleId: 'com.christophercampbell.pregameworldcup',
  );
} 